"""Refactor links

Revision ID: 1c0dd148708a
Revises: 0acbb0f0b1ef
Create Date: 2018-12-29 19:44:12.935317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0dd148708a'
down_revision = '0acbb0f0b1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('officer_id', sa.Integer(), nullable=True))
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'links', 'officers', ['officer_id'], ['id'], ondelete='CASCADE')
    op.execute('UPDATE links SET officer_id = officer_links.officer_id FROM officer_links WHERE links.id = officer_links.link_id')
    op.drop_table('officer_links')
    # ### end Alembic commands ###


def downgrade():
    pass
